INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'ARIEL SILVA' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'ariel_silva';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Ariel Silva' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'ariel_silva';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'ariel silva' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'ariel_silva';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'MARNOLIS PEREZ' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'marnolis_perez';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Marnolis Perez' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'marnolis_perez';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'marnolis perez' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'marnolis_perez';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'ELIZABETH CABRERA' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'elizabeth_cabrera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Elizabeth Cabrera' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'elizabeth_cabrera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'elizabeth cabrera' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'elizabeth_cabrera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'MARTINA PARRA' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'martina_parra';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Martina Parra' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'martina_parra';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'martina parra' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'martina_parra';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'NATALY RIVERA' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'nataly_rivera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Nataly Rivera' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'nataly_rivera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'nataly rivera' FROM ejecutivos_phoenix WHERE mandante = 'Tanner' AND nombre_clave = 'nataly_rivera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'ARIEL SILVA' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'ariel_silva';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Ariel Silva' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'ariel_silva';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'ariel silva' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'ariel_silva';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'MARNOLIS PEREZ' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'marnolis_perez';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Marnolis Perez' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'marnolis_perez';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'marnolis perez' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'marnolis_perez';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'ELIZABETH CABRERA' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'elizabeth_cabrera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Elizabeth Cabrera' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'elizabeth_cabrera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'elizabeth cabrera' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'elizabeth_cabrera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'MARTINA PARRA' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'martina_parra';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Martina Parra' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'martina_parra';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'martina parra' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'martina_parra';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'NATALY RIVERA' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'nataly_rivera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'Nataly Rivera' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'nataly_rivera';
INSERT IGNORE INTO ejecutivos_alias (ejecutivo_id, alias) SELECT id, 'nataly rivera' FROM ejecutivos_phoenix WHERE mandante = 'Santander Consumer Judicial' AND nombre_clave = 'nataly_rivera';